/**
 * Single-blob secret management (optional, Vercel-friendly).
 *
 * In local dev: set individual env vars in .env.
 * In Vercel prod: paste each env var directly (recommended) OR paste one
 * SECRETS_BLOB generated by `pnpm secrets:encrypt`.
 *
 * This module prefers individual env vars (simpler, more reliable on Vercel).
 * The blob is kept for advanced users who want one-line config.
 */

import crypto from "node:crypto";

export type Secrets = {
  authSecret: string;
  googleClientId: string;
  googleClientSecret: string;
  youtubeApiKey: string;
  youtubeClientId: string;
  youtubeClientSecret: string;
  tokenEncKey: string;
  adminEmails: string;
  stripeSecretKey: string;
  stripeWebhookSecret: string;
  paymentProvider?: "mock" | "stripe";
  youtubeRedirectUri?: string;
};

function getMasterKey(): Buffer {
  const k = process.env.SECRETS_MASTER_KEY || process.env.TOKEN_ENC_KEY || "";
  if (!k) {
    return crypto.createHash("sha256").update("dev-fallback-master-key").digest();
  }
  if (k.length === 44 || k.endsWith("=")) {
    try { return Buffer.from(k, "base64"); } catch { /* fallthrough */ }
  }
  return crypto.createHash("sha256").update(k).digest();
}

export function decryptSecrets(blob: string): Secrets {
  const parts = blob.split(".");
  if (parts.length !== 3) throw new Error("Invalid SECRETS_BLOB format");
  const [ivB64, tagB64, encB64] = parts;
  const iv = Buffer.from(ivB64, "base64");
  const tag = Buffer.from(tagB64, "base64");
  const enc = Buffer.from(encB64, "base64");
  const key = getMasterKey();
  const decipher = crypto.createDecipheriv("aes-256-gcm", key, iv);
  decipher.setAuthTag(tag);
  const dec = Buffer.concat([decipher.update(enc), decipher.final()]);
  return JSON.parse(dec.toString("utf8")) as Secrets;
}

export function encryptSecrets(plain: Secrets): string {
  const key = getMasterKey();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const enc = Buffer.concat([cipher.update(JSON.stringify(plain), "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return [iv.toString("base64"), tag.toString("base64"), enc.toString("base64")].join(".");
}

let cached: Secrets | null = null;

/**
 * Get all secrets. Order of precedence:
 *   1. Already-cached value (per process)
 *   2. Individual process.env vars (always available, no decryption needed)
 *   3. SECRETS_BLOB if set (advanced: one-line config)
 */
export function getSecrets(): Secrets {
  if (cached) return cached;
  cached = {
    authSecret: process.env.AUTH_SECRET || "",
    googleClientId: process.env.GOOGLE_CLIENT_ID || "",
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET || "",
    youtubeApiKey: process.env.YOUTUBE_API_KEY || "",
    youtubeClientId: process.env.YOUTUBE_CLIENT_ID || "",
    youtubeClientSecret: process.env.YOUTUBE_CLIENT_SECRET || "",
    tokenEncKey: process.env.TOKEN_ENC_KEY || "",
    adminEmails: process.env.ADMIN_EMAILS || "",
    stripeSecretKey: process.env.STRIPE_SECRET_KEY || "",
    stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || "",
    paymentProvider: (process.env.PAYMENT_PROVIDER as "mock" | "stripe") || "mock",
    youtubeRedirectUri: process.env.YOUTUBE_REDIRECT_URI,
  };
  // Override with blob if present and decrypts successfully
  if (process.env.SECRETS_BLOB) {
    try {
      const fromBlob = decryptSecrets(process.env.SECRETS_BLOB);
      cached = { ...cached, ...fromBlob };
    } catch (e) {
      // Bad blob, keep individual env vars
      console.warn("[secrets] SECRETS_BLOB failed to decrypt, using individual env vars");
    }
  }
  return cached;
}

/** Apply secrets to process.env. Safe to call multiple times. */
export function applySecrets(): void {
  const s = getSecrets();
  if (s.authSecret) process.env.AUTH_SECRET = s.authSecret;
  if (s.googleClientId) process.env.GOOGLE_CLIENT_ID = s.googleClientId;
  if (s.googleClientSecret) process.env.GOOGLE_CLIENT_SECRET = s.googleClientSecret;
  if (s.youtubeApiKey) process.env.YOUTUBE_API_KEY = s.youtubeApiKey;
  if (s.youtubeClientId) process.env.YOUTUBE_CLIENT_ID = s.youtubeClientId;
  if (s.youtubeClientSecret) process.env.YOUTUBE_CLIENT_SECRET = s.youtubeClientSecret;
  if (s.tokenEncKey) process.env.TOKEN_ENC_KEY = s.tokenEncKey;
  if (s.adminEmails) process.env.ADMIN_EMAILS = s.adminEmails;
  if (s.stripeSecretKey) process.env.STRIPE_SECRET_KEY = s.stripeSecretKey;
  if (s.stripeWebhookSecret) process.env.STRIPE_WEBHOOK_SECRET = s.stripeWebhookSecret;
  if (s.paymentProvider) process.env.PAYMENT_PROVIDER = s.paymentProvider;
  if (!process.env.YOUTUBE_REDIRECT_URI && process.env.VERCEL_URL) {
    process.env.YOUTUBE_REDIRECT_URI = `https://${process.env.VERCEL_URL}/api/youtube/callback`;
  }
  if (!process.env.NEXTAUTH_URL && process.env.VERCEL_URL) {
    process.env.NEXTAUTH_URL = `https://${process.env.VERCEL_URL}`;
  }
}
